export interface Route {
  name: string;
  distance: string;
  ascent: string;
  time: string;
  difficulty: "easy" | "moderate" | "challenging" | "strenuous";
  startPostcode: string;
  startDescription: string;
}

export type FellArea =
  | "eastern"
  | "far-eastern"
  | "central"
  | "southern"
  | "northern"
  | "north-western"
  | "western";

export interface Fell {
  slug: string;
  name: string;
  height: number;
  osGridRef: string;
  latitude: number;
  longitude: number;
  wainwrightBook: 1 | 2 | 3 | 4 | 5 | 6 | 7;
  wainwrightVolume: string;
  area: FellArea;
  difficulty: "easy" | "moderate" | "challenging" | "strenuous";
  summitDescription: string;
  walkingDescription: string;
  routes: Route[];
  tips: string;
  nearbyTarns: string[];
  nearbySummits: string[];
  nearbyDining: { name: string; type: string; distance: string }[];
  featured: boolean;
  image?: string;
}

export const FELLS: Fell[] = [
  {
    slug: "scafell-pike",
    name: "Scafell Pike",
    height: 978,
    osGridRef: "NY 215 072",
    latitude: 54.4542,
    longitude: -3.2116,
    wainwrightBook: 4,
    wainwrightVolume: "The Southern Fells",
    area: "southern",
    difficulty: "strenuous",
    summitDescription: "England's highest mountain. The summit is a cairn-strewn plateau with views across the Lake District.",
    walkingDescription: "The classic route from Wasdale Head is the most direct. Expect 6–8 hours for a round trip. The path is rough and rocky in places.",
    routes: [
      { name: "Wasdale Head", distance: "5.6 miles", ascent: "900m", time: "5–6 hours", difficulty: "strenuous", startPostcode: "CA20 1EX", startDescription: "Wasdale Head car park" },
      { name: "Langdale", distance: "8.5 miles", ascent: "1050m", time: "7–8 hours", difficulty: "strenuous", startPostcode: "LA22 9JU", startDescription: "Old Dungeon Ghyll" },
    ],
    tips: "Start early. Take plenty of water. The summit can be busy in summer. Check weather before you go.",
    nearbyTarns: ["Sty Head Tarn", "Sprinkling Tarn"],
    nearbySummits: ["Scafell", "Great End", "Broad Crag"],
    nearbyDining: [{ name: "Wasdale Head Inn", type: "Pub", distance: "0.5 miles" }],
    featured: true,
    image: "/images/fells/scafell-pike.jpg",
  },
  {
    slug: "helvellyn",
    name: "Helvellyn",
    height: 950,
    osGridRef: "NY 342 151",
    latitude: 54.527,
    longitude: -3.0175,
    wainwrightBook: 1,
    wainwrightVolume: "The Eastern Fells",
    area: "eastern",
    difficulty: "challenging",
    summitDescription: "One of the most popular fells in the Lakes. Striding Edge and Swirral Edge are the classic routes.",
    walkingDescription: "Glenridding or Patterdale are the usual starting points. Striding Edge is the famous ridge approach.",
    routes: [
      { name: "Striding Edge", distance: "8 miles", ascent: "850m", time: "6–7 hours", difficulty: "challenging", startPostcode: "CA11 0PD", startDescription: "Glenridding" },
      { name: "Thirlmere", distance: "9 miles", ascent: "900m", time: "6–7 hours", difficulty: "moderate", startPostcode: "CA12 4TW", startDescription: "Thirlmere" },
    ],
    tips: "Striding Edge is exposed. Not for beginners in bad weather. Check conditions before you go.",
    nearbyTarns: ["Red Tarn", "Browncove Tarns"],
    nearbySummits: ["Catstycam", "Nethermost Pike", "Dollywagon Pike"],
    nearbyDining: [{ name: "Travellers Rest", type: "Pub", distance: "1 mile" }],
    featured: true,
    image: "/images/fells/helvellyn.jpg",
  },
  {
    slug: "skiddaw",
    name: "Skiddaw",
    height: 931,
    osGridRef: "NY 260 290",
    latitude: 54.6518,
    longitude: -3.1516,
    wainwrightBook: 5,
    wainwrightVolume: "The Northern Fells",
    area: "northern",
    difficulty: "moderate",
    summitDescription: "The dominant northern fell. A long but gentle ascent from Keswick.",
    walkingDescription: "The tourist path from Keswick is popular. Steady climb rather than steep.",
    routes: [
      { name: "Keswick", distance: "8 miles", ascent: "900m", time: "5–6 hours", difficulty: "moderate", startPostcode: "CA12 5JR", startDescription: "Latrigg car park" },
    ],
    tips: "Can be windy on top. The path is often busy in summer.",
    nearbyTarns: ["Skiddaw Little Man"],
    nearbySummits: ["Skiddaw Little Man", "Lonscale Fell"],
    nearbyDining: [{ name: "The Pheasant", type: "Pub", distance: "2 miles" }],
    featured: true,
  },
  {
    slug: "blencathra",
    name: "Blencathra",
    height: 868,
    osGridRef: "NY 323 277",
    latitude: 54.6398,
    longitude: -3.0498,
    wainwrightBook: 5,
    wainwrightVolume: "The Northern Fells",
    area: "northern",
    difficulty: "challenging",
    summitDescription: "One of the most dramatic fells. Sharp Edge and Hall's Fell Ridge are the classic routes.",
    walkingDescription: "Threlkeld is the usual start. Sharp Edge is a grade one scramble.",
    routes: [
      { name: "Sharp Edge", distance: "6 miles", ascent: "900m", time: "5–6 hours", difficulty: "challenging", startPostcode: "CA12 4SQ", startDescription: "Threlkeld" },
    ],
    tips: "Sharp Edge is not for beginners. Avoid in wet or windy conditions.",
    nearbyTarns: [],
    nearbySummits: ["Bannerdale Crags", "Foulnaze"],
    nearbyDining: [{ name: "Horse and Farrier", type: "Pub", distance: "0.5 miles" }],
    featured: true,
  },
  {
    slug: "great-gable",
    name: "Great Gable",
    height: 899,
    osGridRef: "NY 211 103",
    latitude: 54.4827,
    longitude: -3.2188,
    wainwrightBook: 7,
    wainwrightVolume: "The Western Fells",
    area: "western",
    difficulty: "challenging",
    summitDescription: "A classic fell with a distinctive shape. The summit has a war memorial.",
    walkingDescription: "Wasdale or Honister are the main approaches. Steep in places.",
    routes: [
      { name: "Wasdale", distance: "6 miles", ascent: "900m", time: "5–6 hours", difficulty: "challenging", startPostcode: "CA20 1EX", startDescription: "Wasdale Head" },
    ],
    tips: "The summit can be confusing in mist. Take a compass.",
    nearbyTarns: ["Sty Head Tarn", "Innominate Tarn"],
    nearbySummits: ["Scafell Pike", "Kirk Fell", "Green Gable"],
    nearbyDining: [{ name: "Wasdale Head Inn", type: "Pub", distance: "1 mile" }],
    featured: true,
  },
  {
    slug: "bowfell",
    name: "Bowfell",
    height: 902,
    osGridRef: "NY 244 064",
    latitude: 54.4478,
    longitude: -3.1758,
    wainwrightBook: 5,
    wainwrightVolume: "The Southern Fells",
    area: "southern",
    difficulty: "challenging",
    summitDescription: "A fine mountain with views to Scafell Pike. The Great Slab is a notable feature.",
    walkingDescription: "Langdale is the usual approach. Rocky terrain.",
    routes: [
      { name: "Langdale", distance: "8 miles", ascent: "950m", time: "6–7 hours", difficulty: "challenging", startPostcode: "LA22 9JU", startDescription: "Old Dungeon Ghyll" },
    ],
    tips: "The Band is a long slog. Worth it for the summit.",
    nearbyTarns: ["Sty Head Tarn"],
    nearbySummits: ["Esk Pike", "Crinkle Crags", "Scafell Pike"],
    nearbyDining: [{ name: "Old Dungeon Ghyll", type: "Hotel", distance: "0.5 miles" }],
    featured: false,
  },
  {
    slug: "crinkle-crags",
    name: "Crinkle Crags",
    height: 859,
    osGridRef: "NY 244 048",
    latitude: 54.4332,
    longitude: -3.1758,
    wainwrightBook: 5,
    wainwrightVolume: "The Southern Fells",
    area: "southern",
    difficulty: "challenging",
    summitDescription: "A ridge of five crinkles. The Bad Step is the famous obstacle.",
    walkingDescription: "Langdale approach. The ridge is rough and rewarding.",
    routes: [
      { name: "Langdale", distance: "9 miles", ascent: "900m", time: "6–7 hours", difficulty: "challenging", startPostcode: "LA22 9JU", startDescription: "Old Dungeon Ghyll" },
    ],
    tips: "The Bad Step can be bypassed. Don't feel you have to do it.",
    nearbyTarns: ["Red Tarn"],
    nearbySummits: ["Bowfell", "Cold Pike"],
    nearbyDining: [{ name: "Old Dungeon Ghyll", type: "Hotel", distance: "0.5 miles" }],
    featured: false,
  },
  {
    slug: "high-street",
    name: "High Street",
    height: 828,
    osGridRef: "NY 441 111",
    latitude: 54.4895,
    longitude: -2.8683,
    wainwrightBook: 2,
    wainwrightVolume: "The Far Eastern Fells",
    area: "far-eastern",
    difficulty: "moderate",
    summitDescription: "Named after the Roman road that ran over it. A broad summit with good views.",
    walkingDescription: "Patterdale or Hartsop are the usual starts. A long but gentle ridge.",
    routes: [
      { name: "Patterdale", distance: "10 miles", ascent: "900m", time: "6–7 hours", difficulty: "moderate", startPostcode: "CA11 0PD", startDescription: "Patterdale" },
    ],
    tips: "A good ridge walk. Can be combined with other fells.",
    nearbyTarns: ["Hayeswater", "Small Water"],
    nearbySummits: ["Rampsgill Head", "Thornthwaite Crag"],
    nearbyDining: [{ name: "White Lion", type: "Pub", distance: "1 mile" }],
    featured: false,
  },
  {
    slug: "pike-o-stickle",
    name: "Pike o'Stickle",
    height: 709,
    osGridRef: "NY 273 074",
    latitude: 54.4542,
    longitude: -3.1183,
    wainwrightBook: 5,
    wainwrightVolume: "The Southern Fells",
    area: "southern",
    difficulty: "moderate",
    summitDescription: "A distinctive peak at the head of Langdale. The Stickle Ghyll path is popular.",
    walkingDescription: "Langdale. Steep in places but short.",
    routes: [
      { name: "Langdale", distance: "4 miles", ascent: "600m", time: "3–4 hours", difficulty: "moderate", startPostcode: "LA22 9JU", startDescription: "Old Dungeon Ghyll" },
    ],
    tips: "Good for a shorter day. Combine with Harrison Stickle.",
    nearbyTarns: ["Stickle Tarn"],
    nearbySummits: ["Harrison Stickle", "Pavey Ark"],
    nearbyDining: [{ name: "Old Dungeon Ghyll", type: "Hotel", distance: "0.5 miles" }],
    featured: false,
  },
  {
    slug: "harrison-stickle",
    name: "Harrison Stickle",
    height: 736,
    osGridRef: "NY 281 074",
    latitude: 54.4542,
    longitude: -3.1066,
    wainwrightBook: 5,
    wainwrightVolume: "The Southern Fells",
    area: "southern",
    difficulty: "moderate",
    summitDescription: "The highest of the Langdale Pikes. A rocky summit.",
    walkingDescription: "Langdale. Often combined with Pike o'Stickle.",
    routes: [
      { name: "Langdale", distance: "5 miles", ascent: "650m", time: "4–5 hours", difficulty: "moderate", startPostcode: "LA22 9JU", startDescription: "Old Dungeon Ghyll" },
    ],
    tips: "The Langdale Pikes are a classic. Do them together.",
    nearbyTarns: ["Stickle Tarn"],
    nearbySummits: ["Pike o'Stickle", "Pavey Ark", "Thunacar Knott"],
    nearbyDining: [{ name: "Old Dungeon Ghyll", type: "Hotel", distance: "0.5 miles" }],
    featured: false,
  },
  {
    slug: "fairfield",
    name: "Fairfield",
    height: 873,
    osGridRef: "NY 358 109",
    latitude: 54.4878,
    longitude: -2.9966,
    wainwrightBook: 1,
    wainwrightVolume: "The Eastern Fells",
    area: "eastern",
    difficulty: "challenging",
    summitDescription: "A horseshoe of fells. Fairfield is the centrepiece.",
    walkingDescription: "Rydal or Patterdale. The Fairfield circuit is a classic.",
    routes: [
      { name: "Rydal", distance: "10 miles", ascent: "900m", time: "6–7 hours", difficulty: "challenging", startPostcode: "LA22 9LU", startDescription: "Rydal" },
    ],
    tips: "The horseshoe is a long day. Start early.",
    nearbyTarns: ["Grisedale Tarn"],
    nearbySummits: ["St Sunday Crag", "Dove Crag", "Hart Crag"],
    nearbyDining: [{ name: "Grasmere Hotel", type: "Hotel", distance: "2 miles" }],
    featured: false,
  },
  {
    slug: "coniston-old-man",
    name: "Coniston Old Man",
    height: 803,
    osGridRef: "SD 272 978",
    latitude: 54.3708,
    longitude: -3.1216,
    wainwrightBook: 4,
    wainwrightVolume: "The Southern Fells",
    area: "southern",
    difficulty: "moderate",
    summitDescription: "The dominant fell above Coniston. Old mining remains on the way up.",
    walkingDescription: "Coniston village. A popular and straightforward ascent.",
    routes: [
      { name: "Coniston", distance: "5.5 miles", ascent: "750m", time: "4–5 hours", difficulty: "moderate", startPostcode: "LA21 8EH", startDescription: "Coniston village" },
    ],
    tips: "The quarry path is the most direct. Can be busy.",
    nearbyTarns: ["Low Water", "Goat's Water"],
    nearbySummits: ["Dow Crag", "Brim Fell"],
    nearbyDining: [{ name: "Black Bull", type: "Pub", distance: "0.5 miles" }],
    featured: true,
  },
  {
    slug: "catbells",
    name: "Catbells",
    height: 451,
    osGridRef: "NY 244 199",
    latitude: 54.5758,
    longitude: -3.1758,
    wainwrightBook: 6,
    wainwrightVolume: "The North Western Fells",
    area: "north-western",
    difficulty: "easy",
    summitDescription: "One of the most popular fells. Family-friendly with great views over Derwentwater.",
    walkingDescription: "Hawes End or Skelgill. Short and accessible.",
    routes: [
      { name: "Hawes End", distance: "3.5 miles", ascent: "450m", time: "2–3 hours", difficulty: "easy", startPostcode: "CA12 5UE", startDescription: "Hawes End" },
    ],
    tips: "Very popular. Go early or midweek to avoid crowds.",
    nearbyTarns: [],
    nearbySummits: ["Maiden Moor", "Derwent Fells"],
    nearbyDining: [{ name: "Lodore Falls", type: "Hotel", distance: "2 miles" }],
    featured: true,
  },
  {
    slug: "grisedale-pike",
    name: "Grisedale Pike",
    height: 791,
    osGridRef: "NY 198 219",
    latitude: 54.5932,
    longitude: -3.2188,
    wainwrightBook: 6,
    wainwrightVolume: "The North Western Fells",
    area: "north-western",
    difficulty: "moderate",
    summitDescription: "A distinctive peak above Coledale. Good views to Skiddaw.",
    walkingDescription: "Braithwaite or Coledale. A steady climb.",
    routes: [
      { name: "Braithwaite", distance: "6 miles", ascent: "900m", time: "4–5 hours", difficulty: "moderate", startPostcode: "CA12 5TW", startDescription: "Braithwaite" },
    ],
    tips: "Often combined with Hopegill Head and the Coledale round.",
    nearbyTarns: ["Coledale Hause"],
    nearbySummits: ["Hopegill Head", "Crag Hill"],
    nearbyDining: [{ name: "Royal Oak", type: "Pub", distance: "0.5 miles" }],
    featured: false,
  },
  {
    slug: "causey-pike",
    name: "Causey Pike",
    height: 637,
    osGridRef: "NY 218 209",
    latitude: 54.5832,
    longitude: -3.1966,
    wainwrightBook: 6,
    wainwrightVolume: "The North Western Fells",
    area: "north-western",
    difficulty: "moderate",
    summitDescription: "A distinctive ridge with a conical summit. Part of the Coledale round.",
    walkingDescription: "Braithwaite or Stair. A good ridge walk.",
    routes: [
      { name: "Braithwaite", distance: "5 miles", ascent: "700m", time: "4–5 hours", difficulty: "moderate", startPostcode: "CA12 5TW", startDescription: "Braithwaite" },
    ],
    tips: "The ridge is fun. Good for a half-day.",
    nearbyTarns: [],
    nearbySummits: ["Scar Crags", "Grisedale Pike"],
    nearbyDining: [{ name: "Royal Oak", type: "Pub", distance: "0.5 miles" }],
    featured: false,
  },
  {
    slug: "red-pike-buttermere",
    name: "Red Pike (Buttermere)",
    height: 755,
    osGridRef: "NY 171 161",
    latitude: 54.5216,
    longitude: -3.2466,
    wainwrightBook: 7,
    wainwrightVolume: "The Western Fells",
    area: "western",
    difficulty: "challenging",
    summitDescription: "Red sandstone above Buttermere. Part of the Buttermere fells.",
    walkingDescription: "Buttermere village. Steep in places.",
    routes: [
      { name: "Buttermere", distance: "7 miles", ascent: "900m", time: "5–6 hours", difficulty: "challenging", startPostcode: "CA13 9XA", startDescription: "Buttermere" },
    ],
    tips: "Often combined with High Stile and High Crag.",
    nearbyTarns: ["Bleaberry Tarn"],
    nearbySummits: ["High Stile", "High Crag"],
    nearbyDining: [{ name: "Fish Inn", type: "Pub", distance: "0.5 miles" }],
    featured: false,
  },
  {
    slug: "dale-head",
    name: "Dale Head",
    height: 753,
    osGridRef: "NY 223 153",
    latitude: 54.5158,
    longitude: -3.1916,
    wainwrightBook: 6,
    wainwrightVolume: "The North Western Fells",
    area: "north-western",
    difficulty: "moderate",
    summitDescription: "A fine viewpoint above the Newlands valley. Part of the Newlands round.",
    walkingDescription: "Newlands or Honister. A good circuit.",
    routes: [
      { name: "Honister", distance: "6 miles", ascent: "750m", time: "4–5 hours", difficulty: "moderate", startPostcode: "CA12 5XN", startDescription: "Honister" },
    ],
    tips: "The Newlands round is a classic. Dale Head is the high point.",
    nearbyTarns: ["Dale Head Tarn"],
    nearbySummits: ["Hindscarth", "Robinson"],
    nearbyDining: [{ name: "Honister Slate Mine", type: "Cafe", distance: "0.5 miles" }],
    featured: false,
  },
  {
    slug: "wetherlam",
    name: "Wetherlam",
    height: 763,
    osGridRef: "NY 288 014",
    latitude: 54.3982,
    longitude: -3.0966,
    wainwrightBook: 4,
    wainwrightVolume: "The Southern Fells",
    area: "southern",
    difficulty: "moderate",
    summitDescription: "The highest fell above Coniston. Good views to the Old Man.",
    walkingDescription: "Coniston or Tilberthwaite. A good ridge.",
    routes: [
      { name: "Coniston", distance: "6 miles", ascent: "750m", time: "4–5 hours", difficulty: "moderate", startPostcode: "LA21 8EH", startDescription: "Coniston" },
    ],
    tips: "Often combined with the Coniston Fells.",
    nearbyTarns: ["Levers Water"],
    nearbySummits: ["Swirl How", "Coniston Old Man"],
    nearbyDining: [{ name: "Black Bull", type: "Pub", distance: "0.5 miles" }],
    featured: false,
  },
  {
    slug: "ill-bell",
    name: "Ill Bell",
    height: 757,
    osGridRef: "NY 430 049",
    latitude: 54.4358,
    longitude: -2.8683,
    wainwrightBook: 2,
    wainwrightVolume: "The Far Eastern Fells",
    area: "far-eastern",
    difficulty: "moderate",
    summitDescription: "Part of the Kentmere round. A good ridge walk.",
    walkingDescription: "Kentmere or Troutbeck. The Kentmere horseshoe is a classic.",
    routes: [
      { name: "Kentmere", distance: "12 miles", ascent: "1200m", time: "7–8 hours", difficulty: "challenging", startPostcode: "LA8 9JL", startDescription: "Kentmere" },
    ],
    tips: "The full Kentmere horseshoe is a long day. Ill Bell is one of the summits.",
    nearbyTarns: ["Kentmere Reservoir"],
    nearbySummits: ["Froswick", "Yoke", "High Street"],
    nearbyDining: [{ name: "Kentmere", type: "Village", distance: "1 mile" }],
    featured: false,
  },
  {
    slug: "place-fell",
    name: "Place Fell",
    height: 657,
    osGridRef: "NY 405 169",
    latitude: 54.5316,
    longitude: -2.9066,
    wainwrightBook: 2,
    wainwrightVolume: "The Far Eastern Fells",
    area: "far-eastern",
    difficulty: "moderate",
    summitDescription: "A fine viewpoint above Patterdale. Good views of Ullswater.",
    walkingDescription: "Patterdale or Sandwick. A good half-day.",
    routes: [
      { name: "Patterdale", distance: "5 miles", ascent: "650m", time: "4–5 hours", difficulty: "moderate", startPostcode: "CA11 0PD", startDescription: "Patterdale" },
    ],
    tips: "A good alternative to the busier Helvellyn. Views of Ullswater.",
    nearbyTarns: [],
    nearbySummits: ["Brock Crags", "Angletarn Pikes"],
    nearbyDining: [{ name: "White Lion", type: "Pub", distance: "0.5 miles" }],
    featured: false,
  },
];

export function getFell(slug: string): Fell | undefined {
  return FELLS.find((f) => f.slug === slug);
}

export function getFeaturedFells(): Fell[] {
  return FELLS.filter((f) => f.featured);
}
